/* Generated by tools/vendor/patch-for-r.sh -- do not edit by hand. */
#if !defined(NANOWASM_ASSERT_H)
#define NANOWASM_ASSERT_H

/* Replaces <assert.h> for the vendored toywasm sources. The expression is
   type-checked and its operands count as used, but it is never evaluated
   and nothing can call abort(). */
#undef assert
#define assert(e) ((void)sizeof((e) ? 1 : 0))

#endif /* !defined(NANOWASM_ASSERT_H) */
