## Generated by tools/vendor-toywasm.sh -- do not edit by hand.
## Explicit object list: portable make has no $(wildcard).
TOYWASM_OBJECTS = \
  toywasm/bitmap.o \
  toywasm/cconv.o \
  toywasm/cell.o \
  toywasm/context.o \
  toywasm/decode.o \
  toywasm/dummy_host_func.o \
  toywasm/endian.o \
  toywasm/escape.o \
  toywasm/exec.o \
  toywasm/exec_insn_subr.o \
  toywasm/expr.o \
  toywasm/expr_parser.o \
  toywasm/host_instance.o \
  toywasm/idalloc.o \
  toywasm/import_object.o \
  toywasm/insn.o \
  toywasm/instance.o \
  toywasm/leb128.o \
  toywasm/list.o \
  toywasm/load_context.o \
  toywasm/mem.o \
  toywasm/module.o \
  toywasm/name.o \
  toywasm/options.o \
  toywasm/report.o \
  toywasm/restart.o \
  toywasm/slist.o \
  toywasm/timeutil.o \
  toywasm/type.o \
  toywasm/util.o \
  toywasm/validation.o \
  toywasm/vec.o \
  $(NULL)
