/* Generated by tools/vendor-toywasm.sh -- do not edit by hand. */
#if !defined(_TOYWASM_VERSION_H)
#define _TOYWASM_VERSION_H
#define TOYWASM_VERSION "v76.0.0"
#endif /* !defined(_TOYWASM_VERSION_H) */
