#!/bin/sh
# Vendor toywasm's interpreter library into src/toywasm/. Re-run to upgrade.
#
# Usage: tools/vendor-toywasm.sh [git-ref]
#
# Copies the files listed in tools/vendor/toywasm-files.txt, adapts them to
# R with tools/vendor/patch-for-r.sh, generates the object list and version
# header, and records provenance and checksums in tools/vendor/. Two runs on
# the same ref produce byte-identical trees.
set -eu

REF="${1:-v76.0.0}"
REPO="https://github.com/yamt/toywasm.git"
PKG_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$PKG_ROOT/src/toywasm"
FILES="$PKG_ROOT/tools/vendor/toywasm-files.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

LC_ALL=C
export LC_ALL

echo "Cloning $REPO at $REF ..."
git clone --quiet --depth 1 --branch "$REF" "$REPO" "$TMP/toywasm" 2>/dev/null \
  || { git clone --quiet "$REPO" "$TMP/toywasm"; git -C "$TMP/toywasm" checkout --quiet "$REF"; }

COMMIT="$(git -C "$TMP/toywasm" rev-parse HEAD)"
VERSION="${REF#v}"

rm -rf "$DEST"
mkdir -p "$DEST"
grep -v '^#' "$FILES" | grep -v '^[[:space:]]*$' | while read -r f; do
  [ -f "$TMP/toywasm/lib/$f" ] || { echo "vendor: $f is not in upstream lib/" >&2; exit 1; }
  cp "$TMP/toywasm/lib/$f" "$DEST/$f"
done

cp "$TMP/toywasm/LICENSE" "$PKG_ROOT/inst/TOYWASM_LICENSE"

# The version header CMake would generate from `git describe`.
cat > "$DEST/toywasm_version.h" <<EOT
/* Generated by tools/vendor-toywasm.sh -- do not edit by hand. */
#if !defined(_TOYWASM_VERSION_H)
#define _TOYWASM_VERSION_H
#define TOYWASM_VERSION "$REF"
#endif /* !defined(_TOYWASM_VERSION_H) */
EOT

# Adapt the tree to R before anything is recorded, so the checksums cover
# exactly what gets compiled.
( cd "$PKG_ROOT" && ./tools/vendor/patch-for-r.sh )

# R CMD check flags $(wildcard) as a GNU make extension, so emit an explicit
# object list instead.
{
  echo "## Generated by tools/vendor-toywasm.sh -- do not edit by hand."
  echo "## Explicit object list: portable make has no \$(wildcard)."
  printf 'TOYWASM_OBJECTS = \\\n'
  for f in "$DEST"/*.c; do
    b="$(basename "$f")"
    printf '  toywasm/%s.o \\\n' "${b%.c}"
  done
  echo "  \$(NULL)"
} > "$DEST/objects.mk"

# Provenance, kept beside the manifest rather than inside src/toywasm/: the
# vendor guard treats everything under src/toywasm/ as vendored source.
# Deliberately no date, so a re-run on the same ref changes nothing.
cat > "$PKG_ROOT/tools/vendor/VENDORED" <<EOT
toywasm vendored from $REPO
version: $VERSION
ref:     $REF
commit:  $COMMIT

Regenerate with: tools/vendor-toywasm.sh $REF
Files: tools/vendor/toywasm-files.txt (a subset of upstream lib/).
Local modifications: applied by tools/vendor/patch-for-r.sh; see that script
for what each rewrite does and why. Build configuration lives in
src/toywasm_config.h, and src/toywasm_shim.c replaces upstream's logging and
stdio helpers.
EOT

if command -v sha256sum >/dev/null 2>&1; then SHA_SUM="sha256sum"
elif command -v shasum >/dev/null 2>&1; then SHA_SUM="shasum -a 256"
else echo "vendor: no sha256 tool found" >&2; exit 1; fi

# The local changes are part of what was vendored: a new substitution in
# patch-for-r.sh or a new file in the list changes src/toywasm/ at the same
# upstream commit, and the vendor guard requires the manifest to change with
# it. So the manifest records a digest of both.
LOCAL="$(cd "$PKG_ROOT" && cat tools/vendor/patch-for-r.sh tools/vendor/toywasm-files.txt \
  | $SHA_SUM | cut -c1-16)"
{
  printf 'name\trepo\tref\tcommit\tversion\tdest\tlocal_changes\n'
  printf 'toywasm\t%s\t%s\t%s\t%s\t%s\t%s\n' "$REPO" "$REF" "$COMMIT" "$VERSION" "src/toywasm" "$LOCAL"
} > "$PKG_ROOT/tools/vendor/manifest.tsv"

( cd "$PKG_ROOT" && { find src/toywasm -type f ! -name 'objects.mk' ! -name '*.o'; echo inst/TOYWASM_LICENSE; } \
    | sort | xargs $SHA_SUM ) > "$PKG_ROOT/tools/vendor/checksums.sha256"

echo "Vendored toywasm $REF ($COMMIT) into src/toywasm/"
echo "  $(ls "$DEST"/*.c | wc -l | tr -d ' ') .c, $(ls "$DEST"/*.h | wc -l | tr -d ' ') .h files"
